version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel-app
    ports:
      - "8010:80"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tiket_bus_db
      MYSQL_ROOT_PASSWORD: password_lo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
