[phases.setup]
commands = ["echo 'Setting up PHP 8.1 environment'"]

[phases.install]
commands = ["nix-env -iA nixpkgs.php81"]

[phases.build]
commands = ["composer install --no-dev --optimize-autoloader"]

[phases.start]
commands = ["php artisan serve --host=0.0.0.0 --port=$PORT"]
